apiVersion: v1
kind: Service
metadata:
  name: post-database
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: post-database-statefulset
  ports:
    - port: 65433
      targetPort: 5432
  type: ClusterIP