apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-database-statefulset
  namespace: kfje-namespace
spec:
  serviceName: post-database-statefulset
  selector:
    matchLabels:
      app: post-database-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: post-database-statefulset
    spec:
      containers:
        - name: post-database-statefulset
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: post-database-configmap
          volumeMounts:
            - mountPath: "/data"
              name: post-database-data
  volumeClaimTemplates:
    - metadata:
        name: post-database-data
      spec:
        storageClassName: hostpath
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteMany