apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-pv
  namespace: kfje-namespace
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/evigilans
