apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace }}
  name: post-service-ingress
spec:
  rules:
    - host: posts-kfje.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: post-service
                port:
                  number: 8082