apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post-service-deployment
  ports:
    - port: 8082
      targetPort: 8082