apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: evigilans/post-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: post-service
          env:
            - name: TEST
              value: postsrv
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 30
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
      restartPolicy: Always