apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  namespace: kfje-namespace
spec:
  selector:
    matchLabels:
      app: post-service-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: post-service-deployment
    spec:
      containers:
        - name: post-service-container
          image: evigilans/post-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "pstgrpsw"
      restartPolicy: Always