apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: user-service-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31011