apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service-deployment
  ports:
    - port: 8081
      targetPort: 8081