apiVersion: v1
kind: Service
metadata:
  name: user-database
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: user-database-statefulset
  ports:
    - port: 65432
      targetPort: 5432
  type: ClusterIP