apiVersion: v1
kind: Service
metadata:
  name: user-database
  namespace: kfje-namespace
spec:
  selector:
    app: user-database-statefulset
  ports:
    - port: 65432
      targetPort: 5432
  type: ClusterIP